YOLOV3:
  BACKBONE: "org"
  CFG: "./DeepSort/detector/YOLOv3/cfg/yolo_v3.cfg"
  WEIGHT: "./DeepSort/detector/YOLOv3/weight/yolov3.weights"
  CLASS_NAMES: "./DeepSort/detector/YOLOv3/cfg/coco.names"

  SCORE_THRESH: 0.1
  NMS_THRESH: 0.5
